networks:
  frontend-net:
    driver: bridge

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    command: npm run dev
    ports:
      - 4567:5173
    networks:
      - frontend-net
