name: Release
on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Release
        run: |
          docker build --tag bumessenger/frontend:latest ./ -f ./frontend.dockerfile
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker push bumessenger/frontend:latest
